### ISSUE TITLE
The Global file structure needs to be fixed.

### ISSUE THREAD

**Issue by MSilva95** [01-edu/UX-UI#2]
- Naming the quests properly (instead of ux-1 you need to give a global name for the quest) for example:
 
 `ux-1 -->  "global-name-that-involves-all-exercises"`

- Naming the exercises properly:

    ` ux-1-1  --> user-interviews`
    ` ux-1-2  --> analytics`

**Comment by afeeeling** [comment]
Hi @davhojt and @MSilva95, I changed all the titles on my VSC environment, just need to upload it next Tuesday

**Comment by davhojt** [comment]
Cheers @afeeeling.

Let's mark as done when we see that it is complete.
