### ISSUE TITLE
Projects 1,2,3,4

### ISSUE THREAD

**Issue by MSilva95** [01-edu/UX-UI#6]
General Project review:

- The projects need new audits, it has the same problem as inside the piscines, wrong structure, no Yes/NO questions
- One project is divided in two parts the UI and the UX i suppose, but:
    - The readmes are the same in both parts so it needs some changes as its not relevant to have two readmes with the same info.
    - The structure of the readme is not the same as ours as well, we can accept some of the changes but the part of the presentations we need to think about a solution for that. We don't have the concept of presentations in the curriculum so we need to check if it is possible to have it or not.

**Comment by davhojt** [comment]
Audit questions must evaluate to YES in order for the student to pass that question.

For example:
`###### Does the solution run without errors?`

**Comment by davhojt** [comment]
Example of what a good audit looks like: https://github.com/01-edu/public/tree/master/subjects/push-swap/audit
